### model
model_name_or_path: /home/x_yisen/codes/LLaMA-Factory/output/codellama7b_full_sft  # ✅ 必换成对齐模型
trust_remote_code: true


### method
stage: dpo
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all
pref_beta: 0.1
pref_loss: sigmoid

### dataset
dataset: fine_tune_refactoring_dpo
template: alpaca
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 8

### output
output_dir: saves/codellama7b/lora/dpo_2_on_fine_tune_1
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true

### eval
# 可留空